### ISSUE TITLE
Add support for Go

### ISSUE THREAD

**Issue by steffenfritz** [kkoomen/vim-doge#19]
Please add support for Golang

**Comment by kkoomen** [comment]
I would like to support Go, yet when browsing through the GitHub trending page Go repositories and asking around in IRC chats people mentioned that they don't use a documentation standard when writing Go. They use a simple single-line comment to add some additional commentary but that's it.

If you can provide me with a doc standard that is being used in the Go community I am happy to support Go. If you can't provide this I will close this issue.

**Comment by steffenfritz** [comment]
I'd suggest godoc (which is the standard): https://blog.golang.org/godoc-documenting-go-code

**Comment by kkoomen** [comment]
@steffenfritz That standard is _exactly_ as I just described. They only use a single-line comment and do not use any tags in their comments.

I'll close this issue since Golang can't be supported by DoGe.

Feel free to submit any new issues if you experience any unwanted behaviour in the future. Thanks for your contribution.

**Comment by roeeyn** [comment]
@kkoomen I think your justification for not supporting Golang inside DoGe is great. I think it would be a good idea to put it somewhere in the README so people can understand the reason behind this. Thanks for this plugin!
