### ISSUE TITLE
C++ template for return value leads to failure to insert anything

### ISSUE THREAD

**Issue by rmatpd** [kkoomen/vim-doge#26]
Hello again, another c++ request:

For a line such as:
```cpp
std::vector<std::string> someFunction();
```

My mapping does not trigger anything to be inserted.  I know my mapping is working because another one such as:
```cpp
std::string someOtherFunction();
```

Works great!
```cpp
/**
 * TODO
 * @return TODO
 */
```

Thank you again.

**Comment by kkoomen** [comment]
One small note for your PR: Make sure to use back-ticks ``` ` ``` for code anything in GitHub. Second time I corrected your PR for this.

This issue has been fixed in [v1.5.2](https://github.com/kkoomen/vim-doge/tree/v1.5.2). I'm strictly allowing a certain type of characters within the regex and the part inside the angle bracket `<...>` did not allow the colon `:`. This might occur more often. Just keep repeating making issues since it's an easy fix.

Feel free to submit any new issues if you experience any unwanted behavior in the future. Thanks for your contribution.
