### ISSUE TITLE
Add support for JavaScript class properties

### ISSUE THREAD

**Issue by gbcreation** [kkoomen/vim-doge#29]
Could you please add support for JavaScript class properties? Here are some examples.

**Example 1**

```javascript
class Test {
    classProperty
}
```

generated documentation:

```javascript
class Test {
    /**
     * description
     * @type {*}
     */
    classProperty
}
```

**Example 2**

```javascript
class Test {
    static classProperty
}
```

generated documentation:

```javascript
class Test {
    /**
     * description
     * @static
     * @type {*}
     */
    static classProperty
}
```

**Example 3**

```javascript
class Test {
    classProperty = 'default value'
}
```

generated documentation:

```javascript
class Test {
    /**
     * description
     * @type {string}
     */
    classProperty = 'default value'
}
```
**Example 4**

```javascript
class Test {
    static classProperty = function() {}
}
```

generated documentation:

```javascript
class Test {
    /**
     * description
     * @static
     * @type {Function}
     */
    static classProperty = function() {}
}
```

**Comment by kkoomen** [comment]
Sure. Will work on it. I'll also add support for:
- JavaScript + FlowJS
- TypeScript

The `classProperty` may be defined with a typing with FlowJS or in TypeScript, like so:
```typescript
class Test {
    /**
     * description
     * @type {string}
     */
    classProperty: string = 'default value'
}
```

If this is the case, I'll use this type.

If this is not the case, I suggest to add `@type {[TODO:type]}` which you can jump to easily, since adding additional parsing is a lot of work to get all the scenario's right. This can be done at a later stage if there are enough requests from the community to implement this. Being able to jump to it saves time already.


> ```
> class Test {
>    /**
>     * description
>     * @static
>     * @type {*}
>     */
>    static classProperty
>}
>```

About the `* @type {*}` part: 

I did remove `{*}` in v1.6.0+ for all JavaScript patterns (and every other language) and replaced it with a `TODO` placeholder, since it is more efficient for the user to quickly jump through the types as well to quickly add the parameter type. When using DoGe myself I didn't like it at all that I could only fill in descriptions but no parameter types. This took extra time for me.

It would save you genuinely a second if DoGe would generate `* @type {string}` instead of `* @type {[TODO:type]}`, so I won't implement the additional parsing for now.

**Comment by kkoomen** [comment]
ES6 class properties are supported for JavaScript (including FlowJS) and TypeScript in [v1.9.0](https://github.com/kkoomen/vim-doge/tree/v1.9.0).

Feel free to submit any new issues if you experience any unwanted behaviour in the future. Thanks for your contribution.

**Comment by gbcreation** [comment]
Awesome! Thanks a lot.
