### ISSUE TITLE
TypeScript: implicit return type generates an `@returns` tag

### ISSUE THREAD

**Issue by notpeelz** [kkoomen/vim-doge#312]
**Is your feature request related to a problem?**

Given this TypeScript function:
```ts
function blah(a: number) {
  if (a < 0) {
    return;
  }

  console.log("...");
}
```
DoGe generates the following:
```ts
/**
 * [TODO:description]
 * @param a - [TODO:description]
 *
 * @returns [TODO:description]
 */
```
...even though the function has no return value.

**Describe the solution you'd like**

DoGe could detect if it needs to generate documentation for `@returns` by walking the AST and checking for a `return_statement` with children nodes.

**Comment by kkoomen** [comment]
Hi.

This was done on purpose because javascript does not have return types and always having the `@returns` is a nice add for most javascript-like languages.

This is tricky I'd say, because _not adding_ a return type in TS is basically letting TS infer the type, so it's sort of the same as `any`, but as your solution mentioned, checking  for the return statements would be an option. I'll see what I can do soon.
