### ISSUE TITLE
Enable plugin for Dart (NOT a language request)

### ISSUE THREAD

**Issue by JPFrancoia** [kkoomen/vim-doge#555]
Hi,

Looking at this issue here: https://github.com/kkoomen/vim-doge/issues/303, it looks like Dart is supported by vim-doge. How would I go about enabling it please?

Best

**Comment by kkoomen** [comment]
@JPFrancoia Hi,

I closed the issue at that time because there was no support for Dart yet by the tree-sitter parser, but recently there has been an available parser. If you want this to be implemented then you can make a new request for it by clicking [here](https://github.com/kkoomen/vim-doge/issues/new?assignees=&labels=enhancement&template=language.md&title=Add+support+for+%3Clanguage%3E) and fill in the details. There are other requests and since most Dart dev's don't use Vim for it, I won't make this a high priority and thus won't implement this any time soon, unless there's a ton of devs that +1 your feature request. Another reason is that I'm very busy recently and this project has been build by myself, so I have to find time for these rather big implementations. Dart is also quite a syntax-heavy language, in comparison to languages like Lua, so it does take some time to implement it, which is time I don't have currently.

**Comment by JPFrancoia** [comment]
I understand, thank you for explaining. Good luck!
