### ISSUE TITLE
Add support for Golang

### ISSUE THREAD

**Issue by princebillygk** [kkoomen/vim-doge#598]
Add support for golang with godoc

**Comment by Spuxy** [comment]
Duplicates
issue :#19
The standard doc does not have any tags. Ofc Golang offers a variety options to generate doc but go is not about configuration but convention so it generates by ur naming functions etc... + comment on top of ur code file.

Example:
```go
//Package db provides database operations
package math


//connect func connects into db with specific set of operations
func connect(h Handler) *db.SQL {
    return &db.SQL{h}
}
```

**Comment by kkoomen** [comment]
Godoc is simply a double-forward-slash comment that doesn’t include any tags or other specific structure and this still hasn’t changed when I just had another look at the Godoc specifications. Vim-doge can of course generate a comment but the user wouldn’t have of any benefit since writing two double forward-slash by yourself doesn’t take more than a blink of an eye, plus it is basically the same amount of key presses than you would do to trigger vim-doge. Therefore, there is no use of implementing this for golang.

**Comment by princebillygk** [comment]
@kkoomen but we have to write the name of the function or struct after the double-forward slash. which requires more keypress.
