### ISSUE TITLE
Has DogeCreateDocStandard feature been removed on v4?

### ISSUE THREAD

**Issue by amano-takahisa** [kkoomen/vim-doge#636]
When generating the numpy docstring, I would also like to add an `Example` section header.
I have read [past issues](https://github.com/kkoomen/vim-doge/issues/232#issuecomment-764682841) and thought it could be customized by `DogeCreateDocStandard`, but I also found [the release note](https://github.com/kkoomen/vim-doge/blob/290874b8c67781563971a314fbb0b7632289d178/CHANGELOG.md?plain=1#L10) which sounds like that it is not available from V4.
> Templating limitations: v3 contained basic templating functionality that was custom written, as opposed to v4 that uses [Tera](https://tera.netlify.app/docs)

Is there any way to use a template other than the one currently provided?

**Comment by kkoomen** [comment]
Hi.

Yes, custom user-defined templates has been removed in v3.18.0 already, the release note you're referring to was another issue and not relating to custom user-defined templates. because it was too much of a hassle to maintain.

The Example sections in comments are generally extra fields people can add according to most documentation standards and are mainly used by API devs or those that are building public packages. Vim-doge helps with creating the initial skeleton of the docblock and you can add more fields whenever needed by yourself.
